import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import {
  RotateCcw,
  Bookmark,
  BookmarkCheck,
  GitCompare,
  Download,
  Share2,
  Printer,
  FileText,
  FileCode,
  Info,
  Check,
  AlertTriangle,
  History,
  ArrowRight,
  TrendingUp,
  TrendingDown,
  Minus,
  Briefcase,
} from 'lucide-react';
import type { Scan } from '../types/threat';
import { VerdictGauge } from './VerdictGauge';
import { SeverityChip } from './primitives/SeverityChip';
import { Tooltip } from './primitives/Tooltip';
import { Button } from './primitives/Button';
import { Badge } from './primitives/Badge';
import { Modal } from './primitives/Modal';
import { IndicatorChip } from './domain/IndicatorChip';
import { useToast } from './primitives/Toast';
import { AddToCaseModal } from './domain/AddToCaseModal';

export interface VerdictHeaderProps {
  scan: Scan;
  historyScans: Scan[];
  prevScanId: string | null;
  isFirstScan: boolean;
  historyError: string | null;
  isWatchlisted: boolean;
  isRescanning: boolean;
  onRescan: () => void;
  onToggleWatchlist: () => void;
}

export const VerdictHeader: React.FC<VerdictHeaderProps> = ({
  scan,
  historyScans,
  prevScanId,
  isFirstScan,
  historyError,
  isWatchlisted,
  isRescanning,
  onRescan,
  onToggleWatchlist,
}) => {
  const navigate = useNavigate();
  const toast = useToast();
  const [isComparePickerOpen, setIsComparePickerOpen] = useState(false);
  const [isExportMenuOpen, setIsExportMenuOpen] = useState(false);
  const [isAddToCaseOpen, setIsAddToCaseOpen] = useState(false);
  const [copiedLink, setCopiedLink] = useState(false);

  // Filter prior scans excluding current one
  const priorScans = historyScans.filter((s) => s.id !== scan.id);

  // Copy report URL
  const handleCopyLink = async () => {
    try {
      await navigator.clipboard.writeText(window.location.href);
      setCopiedLink(true);
      toast.success('Report URL copied to clipboard', 'Share Report');
      setTimeout(() => setCopiedLink(false), 2000);
    } catch {
      toast.error('Failed to copy link');
    }
  };

  // Export JSON
  const handleExportJson = () => {
    const dataStr = 'data:text/json;charset=utf-8,' + encodeURIComponent(JSON.stringify(scan, null, 2));
    const downloadAnchor = document.createElement('a');
    downloadAnchor.setAttribute('href', dataStr);
    downloadAnchor.setAttribute('download', `threatlens_${scan.id}.json`);
    document.body.appendChild(downloadAnchor);
    downloadAnchor.click();
    downloadAnchor.remove();
    setIsExportMenuOpen(false);
    toast.success('JSON export downloaded');
  };

  // Export Markdown
  const handleExportMarkdown = () => {
    const factorsMd = scan.factors
      .map((f) => `- **${f.title}** (${f.group}): ${f.points > 0 ? `+${f.points}` : f.points} pts — ${f.description}`)
      .join('\n');

    const mdContent = `# ThreatLens Security Intelligence Report
**Target**: ${scan.target}
**Target Type**: ${scan.target_type.toUpperCase()}
**Scan ID**: \`${scan.id}\`
**Timestamp**: ${new Date(scan.timestamp).toUTCString()}
**Risk Score**: ${scan.risk_score} / 100
**Verdict**: ${scan.risk_level}
**Confidence**: ${scan.confidence}%

## Plain English Assessment
${scan.explanation}

## Recommended Actions
${scan.recommended_action}

## Contributing Factors
${factorsMd || 'No notable factors recorded.'}

---
*Generated by ThreatLens Explainable Intel Layer*
`;
    const dataStr = 'data:text/markdown;charset=utf-8,' + encodeURIComponent(mdContent);
    const downloadAnchor = document.createElement('a');
    downloadAnchor.setAttribute('href', dataStr);
    downloadAnchor.setAttribute('download', `threatlens_${scan.id}.md`);
    document.body.appendChild(downloadAnchor);
    downloadAnchor.click();
    downloadAnchor.remove();
    setIsExportMenuOpen(false);
    toast.success('Markdown report downloaded');
  };

  // Print
  const handlePrint = () => {
    setIsExportMenuOpen(false);
    window.print();
  };

  return (
    <div className="space-y-4">
      {/* Main Header Panel */}
      <div className="p-5 md:p-6 rounded-2xl border border-[var(--border-subtle)] bg-[var(--bg-panel)] shadow-sm">
        <div className="flex flex-col lg:flex-row items-start lg:items-center justify-between gap-6">
          {/* Left: RiskGauge (radial) */}
          <div className="flex items-center gap-5 shrink-0">
            <VerdictGauge score={scan.risk_score} level={scan.risk_level} size={118} />

            <div className="space-y-2">
              <div className="flex items-center gap-2 flex-wrap">
                <SeverityChip
                  severity={scan.risk_level}
                  score={scan.risk_score}
                  size="md"
                  variant="solid"
                />
                {scan.is_demo && <Badge variant="demo" size="xs">Simulated Demo</Badge>}
                <Badge variant="outline" size="xs" className="uppercase font-mono">
                  {scan.target_type}
                </Badge>
              </div>

              {/* Confidence with Tooltip */}
              <div className="flex items-center gap-1.5 text-xs text-[var(--text-secondary)]">
                <span className="font-semibold text-[var(--text-primary)]">{scan.confidence}%</span>
                <span>confidence</span>
                <Tooltip
                  content="Confidence represents multi-source consensus across independent threat intelligence providers and reputation engines."
                  position="top"
                >
                  <button
                    type="button"
                    aria-label="How confidence is calculated"
                    className="text-[var(--text-tertiary)] hover:text-[var(--text-primary)] transition-colors inline-flex items-center"
                  >
                    <Info className="w-3.5 h-3.5" />
                  </button>
                </Tooltip>
              </div>

              {/* Timestamp */}
              <div className="text-[11px] font-mono text-[var(--text-tertiary)]">
                Scanned {new Date(scan.timestamp).toLocaleString()}
              </div>
            </div>
          </div>

          {/* Center/Target: Defanged target identifier */}
          <div className="flex-1 min-w-0 max-w-xl">
            <div className="text-[11px] font-mono uppercase tracking-wider text-[var(--text-tertiary)] mb-1">
              Target Indicator
            </div>
            <div className="flex items-center gap-2 flex-wrap">
              <IndicatorChip
                target={scan.target}
                type={scan.target_type}
                className="max-w-full font-mono text-sm py-1 px-2.5"
              />
            </div>
            {scan.raw_summary?.redirects?.hop_count > 0 && (
              <p className="text-[11px] text-[var(--text-secondary)] mt-1.5">
                Observed {scan.raw_summary.redirects.hop_count} redirect hop
                {scan.raw_summary.redirects.hop_count > 1 ? 's' : ''} leading to destination.
              </p>
            )}
          </div>

          {/* Right: Action cluster */}
          <div className="flex flex-wrap lg:flex-nowrap items-center gap-2 shrink-0 w-full lg:w-auto pt-2 lg:pt-0 border-t lg:border-t-0 border-[var(--border-subtle)]">
            {/* Re-scan */}
            <Button
              variant="secondary"
              size="sm"
              onClick={onRescan}
              disabled={isRescanning}
              aria-label="Re-scan target"
              className="flex items-center gap-1.5"
            >
              <RotateCcw className={`w-3.5 h-3.5 ${isRescanning ? 'animate-spin' : ''}`} />
              <span>{isRescanning ? 'Scanning...' : 'Re-scan'}</span>
            </Button>

            {/* Add to Watchlist */}
            <Button
              variant={isWatchlisted ? 'primary' : 'secondary'}
              size="sm"
              onClick={onToggleWatchlist}
              aria-label={isWatchlisted ? 'Remove from watchlist' : 'Add to watchlist'}
              className="flex items-center gap-1.5"
            >
              {isWatchlisted ? (
                <>
                  <BookmarkCheck className="w-3.5 h-3.5 text-emerald-400" />
                  <span>Watchlisted</span>
                </>
              ) : (
                <>
                  <Bookmark className="w-3.5 h-3.5" />
                  <span>Add to watchlist</span>
                </>
              )}
            </Button>

            {/* Add to Case */}
            <Button
              variant="secondary"
              size="sm"
              onClick={() => setIsAddToCaseOpen(true)}
              aria-label="Add to investigation case"
              className="flex items-center gap-1.5"
            >
              <Briefcase className="w-3.5 h-3.5 text-purple-400" />
              <span>Add to Case</span>
            </Button>

            {/* Compare Scans */}
            <Button
              variant="secondary"
              size="sm"
              onClick={() => setIsComparePickerOpen(true)}
              aria-label="Compare scans"
              className="flex items-center gap-1.5"
            >
              <GitCompare className="w-3.5 h-3.5" />
              <span>Compare scans</span>
            </Button>

            {/* Export Dropdown / Group */}
            <div className="relative">
              <Button
                variant="secondary"
                size="sm"
                onClick={() => setIsExportMenuOpen(!isExportMenuOpen)}
                aria-label="Export report"
                className="flex items-center gap-1.5"
              >
                <Download className="w-3.5 h-3.5" />
                <span>Export</span>
              </Button>

              {isExportMenuOpen && (
                <div
                  role="menu"
                  className="absolute right-0 top-full mt-1.5 z-30 w-44 rounded-lg bg-[var(--bg-elevated)] border border-[var(--border-strong)] p-1 shadow-lg animate-in fade-in duration-100"
                >
                  <button
                    type="button"
                    role="menuitem"
                    onClick={handleExportJson}
                    className="w-full flex items-center gap-2 px-2.5 py-1.5 text-xs text-left rounded-md hover:bg-[var(--bg-inset)] text-[var(--text-primary)] transition-colors cursor-pointer"
                  >
                    <FileCode className="w-3.5 h-3.5 text-blue-400" />
                    <span>Download JSON</span>
                  </button>
                  <button
                    type="button"
                    role="menuitem"
                    onClick={handleExportMarkdown}
                    className="w-full flex items-center gap-2 px-2.5 py-1.5 text-xs text-left rounded-md hover:bg-[var(--bg-inset)] text-[var(--text-primary)] transition-colors cursor-pointer"
                  >
                    <FileText className="w-3.5 h-3.5 text-emerald-400" />
                    <span>Download Markdown</span>
                  </button>
                  <button
                    type="button"
                    role="menuitem"
                    onClick={handlePrint}
                    className="w-full flex items-center gap-2 px-2.5 py-1.5 text-xs text-left rounded-md hover:bg-[var(--bg-inset)] text-[var(--text-primary)] transition-colors cursor-pointer"
                  >
                    <Printer className="w-3.5 h-3.5 text-purple-400" />
                    <span>Print Report</span>
                  </button>
                </div>
              )}
            </div>

            {/* Copy Link */}
            <Button
              variant="ghost"
              size="sm"
              onClick={handleCopyLink}
              aria-label="Copy report link"
              className="flex items-center gap-1.5"
            >
              {copiedLink ? <Check className="w-3.5 h-3.5 text-emerald-500" /> : <Share2 className="w-3.5 h-3.5" />}
              <span className="sr-only">Copy link</span>
            </Button>
          </div>
        </div>
      </div>

      {/* Predecessor Callout / "What changed?" Banner */}
      {prevScanId ? (
        <div className="flex items-center justify-between p-3.5 rounded-xl border border-blue-500/25 bg-blue-500/5 transition-all">
          <div className="flex items-center gap-3">
            <div className="p-2 rounded-lg bg-blue-500/10 text-blue-400">
              <History className="w-4 h-4" />
            </div>
            <div>
              <div className="text-xs font-semibold text-[var(--text-primary)] flex items-center gap-2">
                <span>Prior investigation available</span>
                {scan.delta_vs_previous !== undefined && scan.delta_vs_previous !== null && (
                  <Badge
                    variant={scan.delta_vs_previous > 0 ? 'critical' : scan.delta_vs_previous < 0 ? 'low' : 'neutral'}
                    size="xs"
                    className="font-mono font-bold"
                  >
                    {scan.delta_vs_previous > 0 ? (
                      <span className="flex items-center gap-0.5">
                        <TrendingUp className="w-3 h-3" /> +{scan.delta_vs_previous} pts
                      </span>
                    ) : scan.delta_vs_previous < 0 ? (
                      <span className="flex items-center gap-0.5">
                        <TrendingDown className="w-3 h-3" /> {scan.delta_vs_previous} pts
                      </span>
                    ) : (
                      <span className="flex items-center gap-0.5">
                        <Minus className="w-3 h-3" /> 0 unchanged
                      </span>
                    )}
                  </Badge>
                )}
              </div>
              <p className="text-[11px] text-[var(--text-secondary)] mt-0.5">
                Compare telemetry evolution, new indicators, and redirect hops against scan{' '}
                <code className="text-blue-400">{prevScanId}</code>.
              </p>
            </div>
          </div>

          <Button
            variant="primary"
            size="sm"
            onClick={() => navigate(`/compare/${prevScanId}/${scan.id}`)}
            className="flex items-center gap-1.5 shrink-0"
          >
            <span>What changed?</span>
            <ArrowRight className="w-3.5 h-3.5" />
          </Button>
        </div>
      ) : isFirstScan ? (
        <div className="flex items-center justify-between p-3.5 rounded-xl border border-[var(--border-subtle)] bg-[var(--bg-panel)]">
          <div className="flex items-center gap-3">
            <div className="p-2 rounded-lg bg-[var(--bg-inset)] text-[var(--text-tertiary)]">
              <History className="w-4 h-4" />
            </div>
            <div>
              <div className="text-xs font-medium text-[var(--text-primary)]">
                This is the first scan recorded for this target.
              </div>
              <p className="text-[11px] text-[var(--text-secondary)] mt-0.5">
                Future scans will appear here to enable automated verdict drift detection.
              </p>
            </div>
          </div>
          {!isWatchlisted && (
            <Button variant="secondary" size="xs" onClick={onToggleWatchlist}>
              Add to watchlist
            </Button>
          )}
        </div>
      ) : historyError ? (
        <div className="flex items-center gap-2 p-3 rounded-xl border border-red-500/30 bg-red-500/10 text-xs text-red-400">
          <AlertTriangle className="w-4 h-4 shrink-0" />
          <span>Failed to retrieve historical drift comparisons: {historyError}</span>
        </div>
      ) : null}

      {/* Compare Scans Picker Modal */}
      <Modal
        isOpen={isComparePickerOpen}
        onClose={() => setIsComparePickerOpen(false)}
        title="Compare Scans for this Target"
        description="Select a prior scan to compare against the current investigation."
        size="md"
      >
        <div className="space-y-3 py-1">
          {priorScans.length > 0 ? (
            <div className="divide-y divide-[var(--border-subtle)] border border-[var(--border-subtle)] rounded-lg overflow-hidden max-h-72 overflow-y-auto">
              {priorScans.map((prior) => (
                <button
                  key={prior.id}
                  type="button"
                  onClick={() => {
                    setIsComparePickerOpen(false);
                    navigate(`/compare/${prior.id}/${scan.id}`);
                  }}
                  className="w-full flex items-center justify-between p-3 text-left hover:bg-[var(--bg-inset)] transition-colors cursor-pointer group"
                >
                  <div className="space-y-1">
                    <div className="flex items-center gap-2">
                      <span className="font-mono text-xs font-bold text-[var(--text-primary)] group-hover:text-blue-400 transition-colors">
                        {prior.id}
                      </span>
                      <SeverityChip severity={prior.risk_level} score={prior.risk_score} size="xs" />
                    </div>
                    <div className="text-[11px] text-[var(--text-secondary)]">
                      {new Date(prior.timestamp).toLocaleString()}
                    </div>
                  </div>
                  <ArrowRight className="w-4 h-4 text-[var(--text-tertiary)] group-hover:text-blue-400 transition-colors" />
                </button>
              ))}
            </div>
          ) : (
            <div className="p-6 text-center text-xs text-[var(--text-secondary)] space-y-2">
              <History className="w-6 h-6 mx-auto text-[var(--text-tertiary)]" />
              <p>No prior scans found for this target.</p>
              <p className="text-[11px] text-[var(--text-tertiary)]">
                Re-scan or run another analysis to generate multiple data points.
              </p>
            </div>
          )}
        </div>
      </Modal>

      <AddToCaseModal
        isOpen={isAddToCaseOpen}
        onClose={() => setIsAddToCaseOpen(false)}
        scanId={scan.id}
        scanTarget={scan.target}
      />
    </div>
  );
};
