"""
Plain English section headers for threat reports.
Body text is dynamically generated by LLM reasoning (Groq/Cloudflare/Mistral).
No template fallbacks: if AI reasoning is unavailable, an error state is displayed.
"""

SECTION_WHAT_THIS_IS = "What this is"
SECTION_WHAT_TO_DO = "What to do"
SECTION_WHO_SHOULD_CARE = "Who should care"


def get_section_headers():
    return {
        "what_this_is": SECTION_WHAT_THIS_IS,
        "what_to_do": SECTION_WHAT_TO_DO,
        "who_should_care": SECTION_WHO_SHOULD_CARE,
    }
